In [1]:
# Correct T_lidar_to_camera calibration data

import numpy as np

# Populate the transformation matrix
T_lidar_camera = np.array([
    [0.254022, -0.17011, -0.952121, -0.186921],
    [-0.967256, -0.0365638, 0.29786, -0.0395574],
    [-0.390507, -0.916646, 0.0599436, 0.0939933],
    [0, 0, 0, 1]
])

# Extract the 3x3 rotation matrix
R = T_lidar_camera[:3, :3]

# Create 180-degree rotation around yaw (z-axis)
yaw_rotation = np.array([
    [-1, 0, 0],
    [0, -1, 0],
    [0, 0, 1]
])

# Apply the rotation
R_rotated = yaw_rotation @ R

# Create the new transformation matrix
T_rotated = np.eye(4)
T_rotated[:3, :3] = R_rotated
T_rotated[:3, 3] = T_lidar_camera[:3, 3]

print("Original rotation matrix:")
print(R)
print("\nRotated rotation matrix:")
print(R_rotated)
print("\nNew transformation matrix:")
print(T_rotated)

Original rotation matrix:
[[ 0.254022  -0.17011   -0.952121 ]
 [-0.967256  -0.0365638  0.29786  ]
 [-0.390507  -0.916646   0.0599436]]

Rotated rotation matrix:
[[-0.254022   0.17011    0.952121 ]
 [ 0.967256   0.0365638 -0.29786  ]
 [-0.390507  -0.916646   0.0599436]]

New transformation matrix:
[[-0.254022   0.17011    0.952121  -0.186921 ]
 [ 0.967256   0.0365638 -0.29786   -0.0395574]
 [-0.390507  -0.916646   0.0599436  0.0939933]
 [ 0.         0.         0.         1.       ]]
